# Generated by Django 5.0.7 on 2024-07-23 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contact_no', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('product_interested', models.CharField(choices=[('ISPIN', 'ISPIN'), ('SCAI', 'SCAI'), ('Both', 'Both')], default='ISPIN', max_length=5)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
